# Generated by Django 5.2.4 on 2025-08-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужской"), ("F", "Женский")],
                max_length=1,
                null=True,
            ),
        ),
    ]
