# Generated by Django 5.2.4 on 2025-08-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_god',
            field=models.BooleanField(default=False, help_text='Абсолютные права', verbose_name='Создатель системы'),
        ),
    ]
