# Generated by Django 5.2.4 on 2025-08-03 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(unique=True)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Ожидает партнера'), ('in_progress', 'В процессе'), ('resolved', 'Разрешен'), ('cancelled', 'Отменен'), ('abandoned', 'Заброшен')], default='pending', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('progress', models.FloatField(default=0.0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_creator', models.BooleanField(default=False)),
                ('deleted_by_partner', models.BooleanField(default=False)),
                ('truce_status', models.CharField(choices=[('none', 'Нет предложения'), ('pending', 'Ожидает ответа'), ('accepted', 'Принято')], default='none', max_length=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conflicts', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnered_conflicts', to=settings.AUTH_USER_MODEL)),
                ('truce_initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_truces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConflictEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('truce_proposed', 'Предложено перемирие'), ('truce_accepted', 'Перемирие принято'), ('truce_declined', 'Перемирие отклонено'), ('conflict_delete', 'Конфликт удален'), ('conflict_cancel', 'Конфликт отменен'), ('conflict_join_success', 'Пользователь успешно присоединен')], max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conflicts.conflict')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConflictItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('reason', 'Причина конфликта'), ('description', 'Описание ситуации'), ('impact', 'Влияние на стороны'), ('proposal', 'Предложение решения')], max_length=100)),
                ('is_agreed', models.BooleanField(default=False)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='conflicts.conflict')),
                ('agreed_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreed_in_conflicts', to='conflicts.optionchoice')),
                ('available_options', models.ManyToManyField(related_name='used_in_items', to='conflicts.optionchoice')),
                ('creator_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_by_creators', to='conflicts.optionchoice')),
                ('partner_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_by_partners', to='conflicts.optionchoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
