# Generated by Django 5.2.4 on 2025-10-03 23:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает партнера"),
                            ("in_progress", "В процессе"),
                            ("resolved", "Разрешен"),
                            ("cancelled", "Отменен"),
                            ("abandoned", "Заброшен"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("progress", models.FloatField(default=0.0)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_creator", models.BooleanField(default=False)),
                ("deleted_by_partner", models.BooleanField(default=False)),
                (
                    "truce_status",
                    models.CharField(
                        choices=[
                            ("none", "Нет предложения"),
                            ("pending", "Ожидает ответа"),
                            ("accepted", "Принято"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partnered_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "truce_initiator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_truces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConflictItemModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("creator_choice_value", models.TextField(blank=True, null=True)),
                ("partner_choice_value", models.TextField(blank=True, null=True)),
                ("agreed_choice_value", models.TextField(blank=True, null=True)),
                ("is_agreed", models.BooleanField(default=False)),
                (
                    "conflict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="conflicts.conflictmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConflictEventModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("truce_proposed", "Предложено перемирие"),
                            ("truce_accepted", "Перемирие принято"),
                            ("truce_declined", "Перемирие отклонено"),
                            ("conflict_delete", "Конфликт удален"),
                            ("conflict_cancel", "Конфликт отменен"),
                            (
                                "conflict_join_success",
                                "Пользователь успешно присоединен",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "initiator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conflict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="conflicts.conflictmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
