# Generated by Django 5.2.4 on 2025-10-01 20:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conflicts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConflictEvent",
            new_name="ConflictEventModel",
        ),
        migrations.RenameModel(
            old_name="ConflictItem",
            new_name="ConflictItemModel",
        ),
        migrations.RenameModel(
            old_name="Conflict",
            new_name="ConflictModel",
        ),
        migrations.RenameModel(
            old_name="OptionChoice",
            new_name="OptionChoiceModel",
        ),
    ]
